### ISSUE TITLE
Failed to read a Public Key

### ISSUE THREAD

**Issue by harshpm7** [boschresearch/XDK_on_Ethereum#1]

**Comment by lamecat-yang** [comment]
Hi, can you be more specific about your question?

**Comment by harshpm7** [comment]
Hey there,

Thank you for your response. But I solved the issue. I wasnt able to
configure the IP address I guess.Still not sure why was the issue, am
looking into it.
Still thank you for your time and sorry for the inconvenience caused.

Thanks & Regards,
Harsh Mashru.

**Comment by lamecat-yang** [comment]
Nothing to be done. Issue closed.
